### ISSUE TITLE
$(....).modal is not a function .. i am using it with create-react-app ...

### ISSUE THREAD

**Issue by get4prince** [react-materialize/react-materialize#566]
$(.....).modal is not a funtion showing when i am trying to add react no trigger model

**Actual behavior:** [What actually happens]

### Versions

**react-materialize:** 2.3.2
**react:**16.4.1

**Comment by alextrastero** [comment]
Just read that you are using `create-react-app`, you need to make sure you are including the JS assets properly (jquery and materializejs)

**Comment by get4prince** [comment]
No compatible version found: materialize@^0.100.2  error while installing ..

**Comment by get4prince** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#000000">
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/ss.css">

    <title>BePositiveApp</title>
  </head>
  <body>
    <noscript>
      You need to enable JavaScript to run this app.
    </noscript>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
    <script src="jj.js"></script>
    <div id="root"></div>
  </body>
</html>


i think its perfect..

**Comment by get4prince** [comment]
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#000000">
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/ss.css">

    <title>BePositiveApp</title>
  </head>
  <body>
    <noscript>
      You need to enable JavaScript to run this app.
    </noscript>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
    <script src="jj.js"></script>
    <div id="root"></div>
  </body>
</html>
`
i think its perfect..

**Comment by get4prince** [comment]
https://react-materialize.github.io/#/modals
no trigger modal is not working ... saying error  => $(......).modal is not a function

**Comment by kauly** [comment]
Why 'document.getElementById('foo')'  doesn't work?

**Comment by sakshamjain1398** [comment]
I am facing the same issue and working on create-react-app too. My modal works if i am on version of materialize css less than 0.100.0 but i want to use fullWidth slider which works in version 0.100.0 or newer versions.

**Comment by get4prince** [comment]
i do resolved it by my own .. 
but $().modal(); not working by include $ for jquery on react side ... 
this only work when we add $().modal() on connected js file from html of react ..
